---
 - name: VLAN Automation with Ansible on HP Com7 Devices
   hosts: switches 
   gather_facts: no
   connection: local
   vars_files:
      - vars-hp-interface-vlan-config.yml 
   tasks:
     - debug: var=interface_name
     - name: Configure interface
       comware_interface:
         name: "{{ interface_name }}"
         description: 'ANSIBLE CONFIGURED THIS' 
         username: "{{ username }}" 
         password: "{{ password }}"
         hostname: "{{ inventory_hostname }}"
   #  - name: Configure vlans on interface
   #    comware_switchport: 
   #      name: "{{ interface_name }}"
   #      link_type: trunk
   #      permitted_vlans: "{{ vlans }}"
   #      username: "{{ username }}" 
   #      password: "{{ password }}" 
   #      hostname: "{{ inventory_hostname }}"
